server:
  port: 8081

  #spring:
  #  application:
  #    name: user-service
  #
  ratelimiter:
    instances:
      #      RateLimiter object used in RateLimitingService.basicExample()
      #      basicExample:
      #        #1 request di qua
      #        limitForPeriod: 1
      #        # trong 10s
      #        limitRefreshPeriod: 10s
      #        # thời gian requet tiếp theo vào đợi là 5s
      #        timeoutDuration: 10s
      #
      #      # RateLimiter object used in RateLimitingService.timeoutExample()
      timeoutExample:
        limitForPeriod: 1
        limitRefreshPeriod: 1s
        timeoutDuration: 250ms
#
#      # RateLimiter object used in RateLimitingService.multipleRateLimitsExample()
#      multipleRateLimiters_rps_limiter:
#        limitForPeriod: 2
#        limitRefreshPeriod: 1s
#        timeoutDuration: 2s
#
#      multipleRateLimiters_rpm_limiter:
#        limitForPeriod: 40
#        limitRefreshPeriod: 1m
#        timeoutDuration: 2s
#
#      # RateLimiter object used in RateLimitingService.changeLimitsExample()
#      changeLimitsExample:
#        limitForPeriod: 1
#        limitRefreshPeriod: 1s
#        timeoutDuration: 1s
#
#       RateLimiter object used in RateLimitingService.retryAndRateLimitExample()
#      retryAndRateLimitExample:
#        limitForPeriod: 1
#        limitRefreshPeriod: 1s
#        timeoutDuration: 250ms

#      # RateLimiter object used in RateLimitingService.rateLimiterEventsExample()
#      rateLimiterEventsExample:
#        limitForPeriod: 1
#        limitRefreshPeriod: 1s
#        timeoutDuration: 50ms
#
#      # RateLimiter object used in RateLimitingService.fallbackExample()
#      fallbackExample:
#        limitForPeriod: 1
#        limitRefreshPeriod: 1s
#        timeoutDuration: 500ms
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
