server:
  port: 8081


spring:
  application:
    name: department-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: https://subprj-config-server.herokuapp.com/


#spring:
#  application:
#    name: DEPARTMENT-SERVICE
#
eureka:
  client:
    register-with-eureka:
      value: true
    fetch-registry:
      value: true;
    service-url:
      defaultZone: https://subprj-discovery.herokuapp.com/eureka
#server:
#  port: 8081
#
#spring:
#  application:
#    name: user-service
#
resilience4j:
  retry:
    instances:
      basic:
        #Số lần thử tối đa (bao gồm cả cuộc gọi đầu tiên là lần thử đầu tiên)
        maxRetryAttemps:  5
        #Khoảng thời gian chờ cố định giữa các lần thử lại
        waitDuration:  3s
#server:
#  port: 8081
#
#  #spring:
#  #  application:
#  #    name: user-service
#  #
  ratelimiter:
    instances:
      #      RateLimiter object used in RateLimitingService.basicExample()
      #      basicExample:
      #        #1 request di qua
      #        limitForPeriod: 1
      #        # trong 10s
      #        limitRefreshPeriod: 10s
      #        # thời gian requet tiếp theo vào đợi là 5s
      #        timeoutDuration: 10s
      #
      #      # RateLimiter object used in RateLimitingService.timeoutExample()
      timeoutExample:
        limitForPeriod: 1
        limitRefreshPeriod: 1s
        timeoutDuration: 250ms